name: pumpkin
channels:
  - conda-forge
  - defaults
dependencies:
  - altair_saver==0.5.0=py_0
  - requests[version='>=2.24.0']
  - pandas[version='>=1.3.*']
  - vega_datasets=0.9.0
  - ipykernel=6.5.1
  - altair==4.1.0=py_1
  - graphviz=2.49.3
  - python-graphviz=0.19
  - scikit-learn[version='>=1.0']
  - altair_data_server==0.4.1=py_0
  - pandoc=2.16.2
  - altair_viewer==0.4.0=pyhd8ed1ab_0
  - matplotlib[version='>=3.2.2']
  - docopt=0.6.2
